### ISSUE TITLE
icones qui ne s'affichent pas 

### ISSUE THREAD

**Issue by jululule** [Shuunen/recipes#3]
![image](https://user-images.githubusercontent.com/19534434/80982377-8982a580-8e2b-11ea-8aa1-f4b6d60dbe8d.png)

Version 78.0.3904.87 (Build officiel) (64 bits)
windows 10

**Comment by Shuunen** [comment]
héhé ok c'est corrigé dans la version suivante ^^ 

pour info Chrome 78 date d'octobre 2019 et Chrome 79 de décembre 2019
